---
- name: Create Local-Admin user on VyOS switches
  hosts: switches
  gather_facts: no
  vars:
    vyos_username: "Local-Admin"
    vyos_password: "WGU123"
  tasks:
    - name: Create Local-Admin user with admin privileges
      ansible.netcommon.cli_config:
        config:
          - set system login user {{ vyos_username }} authentication plaintext-password {{ vyos_password }}
          - set system login user {{ vyos_username }} level admin
        save_when: changed

    - name: Commit and save configuration
      ansible.netcommon.cli_command:
        command: 'save'
      register: save_output

    - name: Display save output
      debug:
        var: save_output.stdout_lines
