---
- name: Create Local-Admin user on VyOS switches using raw module
  hosts: switches
  gather_facts: no
  vars:
    vyos_username: "Local-Admin"
    vyos_password: "WGU123"
  tasks:
    - name: Enter configuration mode
      raw: configure

    - name: Set user authentication
      raw: set system login user {{ vyos_username }} authentication plaintext-password {{ vyos_password }}

    - name: Set user level
      raw: set system login user {{ vyos_username }} level admin

    - name: Commit configuration changes
      raw: commit

    - name: Save configuration
      raw: save

    - name: Exit configuration mode
      raw: exit
