---
- name: Create local user accounts on switches, desktops, and test boxes
  hosts: all
  gather_facts: no

  tasks:

    - name: Create Local-Admin user on switches
      when: "'switches' in group_names"
      ios_user:
        name: "Local-Admin"
        password: "WGU123"
        privilege: 15
        state: present

    - name: Create DesktopUsers on Windows desktops
      when: "'windows_desktops' in group_names"
      vars:
        users:
          - name: "DesktopUser1"
          - name: "DesktopUser2"
          - name: "DesktopUser3"
          - name: "DesktopUser4"
      win_user:
        name: "{{ item.name }}"
        password: "WGU123"
        groups:
          - Administrators
        state: present
      loop: "{{ users }}"

    - name: Create TestUser1 on test_box_acct
      when: inventory_hostname == 'test_box_acct'
      user:
        name: "TestUser1"
        password: "{{ 'WGU123' | password_hash('sha512') }}"
        groups: "sudo"
        shell: /bin/bash
        state: present

    - name: Create TestUser2 on test_box_mgmt
      when: inventory_hostname == 'test_box_mgmt'
      user:
        name: "TestUser2"
        password: "{{ 'WGU123' | password_hash('sha512') }}"
        groups: "sudo"
        shell: /bin/bash
        state: present
