---
- name: Admin and user account creation playbook
  hosts: all
  become: yes
  tasks:
  
    - name: Create admin user on EXOS switches
      when: "'switches' in group_names"
      vars:
        admin_username: "admin"
      ansible.builtin.user:
        name: "{{ admin_username }}"
        state: present
        password: "{{ admin_password | default('') }}"  # EXOS switches have no password

    - name: Create users on Windows workstations
      when: "'workstations' in group_names and ansible_facts.os_family == 'Windows'"
      win_user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        groups: Administrators
        state: present
      loop:
        - { name: "DesktopUser1", password: "P@ssw0rd1" }
        - { name: "DesktopUser2", password: "P@ssw0rd2" }
        - { name: "DesktopUser3", password: "P@ssw0rd3" }
        - { name: "DesktopUser4", password: "P@ssw0rd4" }
      
    - name: Create test users on Linux workstations
      when: "'workstations' in group_names and ansible_facts.os_family == 'Debian'"
      ansible.builtin.user:
        name: "{{ item.name }}"
        password: "{{ item.password | password_hash('sha512') }}"
        groups: "{{ item.groups }}"
        state: present
      loop:
        - { name: "TestUser1", password: "P@ssw0rd1", groups: "acct_network" }
        - { name: "TestUser2", password: "P@ssw0rd2", groups: "mgmt_network" }

    - name: Ensure sudo privileges for TestUser1 and TestUser2
      when: "'workstations' in group_names and ansible_facts.os_family == 'Debian'"
      ansible.builtin.lineinfile:
        path: "/etc/sudoers"
        line: "{{ item }} ALL=(ALL) NOPASSWD:ALL"
        validate: '/usr/sbin/visudo -cf %s'
      loop:
        - "TestUser1"
        - "TestUser2"
