---
- name: Create local user accounts on switches, desktops, and test boxes
  hosts: all
  become: yes
  vars:
    users:
      switches:
        - name: "admin"
          password: "{{ 'adminPassword' | password_hash('sha512') }}"
          privilege: "15"
      windows_desktops:
        - name: "DesktopUser1"
          password: "{{ 'DesktopPassword1' }}"
          groups: "Administrators"
        - name: "DesktopUser2"
          password: "{{ 'DesktopPassword2' }}"
          groups: "Administrators"
        - name: "DesktopUser3"
          password: "{{ 'DesktopPassword3' }}"
          groups: "Administrators"
        - name: "DesktopUser4"
          password: "{{ 'DesktopPassword4' }}"
          groups: "Administrators"
      test_boxes:
        - name: "TestUser1"
          password: "{{ 'TestPassword1' | password_hash('sha512') }}"
          groups: "sudo"
        - name: "TestUser2"
          password: "{{ 'TestPassword2' | password_hash('sha512') }}"
          groups: "sudo"

  tasks:
    - name: Ensure user accounts on switches
      when: "'switch' in inventory_hostname"
      user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        state: present
        groups: "{{ item.privilege | default('') }}"
      with_items: "{{ users.switches }}"

    - name: Ensure user accounts on Windows desktops
      when: "'workstation' in inventory_hostname and inventory_hostname != 'workstation5' and inventory_hostname != 'workstation6'"
      win_user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        state: present
        groups: "{{ item.groups }}"
      with_items: "{{ users.windows_desktops }}"

    - name: Ensure user accounts on Linux test boxes
      when: "'workstation5' in inventory_hostname or 'workstation6' in inventory_hostname"
      user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        state: present
        groups: "{{ item.groups }}"
      with_items: "{{ users.test_boxes }}"

    - name: Add the user accounts to sudoers
      when: "'workstation5' in inventory_hostname or 'workstation6' in inventory_hostname"
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: "^{{ item.name }}"
        line: "{{ item.name }} ALL=(ALL) NOPASSWD: ALL"
      with_items: "{{ users.test_boxes }}"
