---
- name: Create user accounts on switches, desktops, and test boxes
  hosts: all
  gather_facts: no
  vars:
    vyos_username: "Local-Admin"
    vyos_password: "WGU123"
    desktop_users:
      - "DesktopUser1"
      - "DesktopUser2"
      - "DesktopUser3"
      - "DesktopUser4"
    test_users:
      - name: "TestUser1"
        host: "test_box_acct"
      - name: "TestUser2"
        host: "test_box_mgmt"

  tasks:
    - name: Install vyos.vyos collection
      ansible.builtin.meta: require_collection
      collections:
        - vyos.vyos

    - name: Create Local-Admin user on VyOS switches
      when: "'switches' in group_names"
      vyos.vyos.vyos_config:
        lines:
          - set system login user {{ vyos_username }} authentication plaintext-password {{ vyos_password }}
          - set system login user {{ vyos_username }} level admin
      connection: network_cli
      vars:
        ansible_network_os: vyos.vyos.vyos

    - name: Save configuration on VyOS switches
      when: "'switches' in group_names"
      vyos.vyos.vyos_config:
        save: yes
      connection: network_cli
      vars:
        ansible_network_os: vyos.vyos.vyos

    - name: Create DesktopUsers on Windows desktops
      when: "'windows_desktops' in group_names"
      win_user:
        name: "{{ item }}"
        password: "WGU123"
        groups:
          - Administrators
        state: present
      loop: "{{ desktop_users }}"

    - name: Create Test Users on Linux Test Boxes
      when: inventory_hostname == item.host
      user:
        name: "{{ item.name }}"
        password: "{{ 'WGU123' | password_hash('sha512') }}"
        groups: sudo
        shell: /bin/bash
        state: present
      loop: "{{ test_users }}"
