---
- name: Create user accounts on switches, desktops, and test boxes
  hosts: all
  gather_facts: no
  vars:
    switch_username: "Local-Admin"
    switch_password: "WGU123"
    desktop_users:
      - "DesktopUser1"
      - "DesktopUser2"
      - "DesktopUser3"
      - "DesktopUser4"
    test_users:
      - name: "TestUser1"
        host: "test_box_acct"
      - name: "TestUser2"
        host: "test_box_mgmt"

  tasks:
    - name: Create Local-Admin user on EXOS switches
      when: "'switches' in group_names"
      extremenetworks.exos.exos_user:
        username: "{{ switch_username }}"
        password: "{{ switch_password }}"
        privilege: rw
        state: present

    - name: Create DesktopUsers on Windows desktops
      when: "'windows_desktops' in group_names"
      win_user:
        name: "{{ item }}"
        password: "WGU123"
        groups:
          - Administrators
        state: present
      loop: "{{ desktop_users }}"

    - name: Create Test Users on Linux Test Boxes
      when: inventory_hostname == item.host
      user:
        name: "{{ item.name }}"
        password: "{{ 'WGU123' | password_hash('sha512') }}"
        groups: sudo
        shell: /bin/bash
        state: present
      loop: "{{ test_users }}"
